var countries = {
  common: [
    'BY',
    'UA',
    'RU',
    'PL',
    'Germany',
    'BG',
    'CZ',
    'LT',
    'LV',
    'EE',
    'Moldova',
    'CH',
    'FR',
    'LI',
    'SE',
    'RU-MOW',
    'RU-SPE',
    'RU-LEN',
    'Iran',
    'Denmark',
    'Finland',
  ],
  ulad: ['GB', 'PT', 'US', 'US-CA', 'US-WA', 'MX', 'CU', 'RU-KDA', 'GE', 'US-NV', 'US-MA', 'US-NY', 'US-OR', 'Canada', 'CA-BC', 'US-HI', 'CA-ON', 'CA-QC', 'RU-MOS', 'RU-KGD', 'RU-TA'],
  marie: ['IT', 'NO', 'TR', 'RU-KR', 'RU-MUR', 'RU-PSK', 'RU-NGR']
};
